### ISSUE TITLE
Add organizer name in mobile event page

### ISSUE THREAD

**Issue by sureshmurali** [Lakshman-LD/LetsMeetUp#107]

**Comment by lakshmantgld** [comment]
Haven't added this already ?

**Comment by lakshmantgld** [comment]
Change the 3 stepper to 2 stepper.

**Comment by sureshmurali** [comment]
Stepper is irrelevant to this issue. 

Added organizer name in Mobile devices.
<img width="288" alt="screen shot 2017-02-22 at 9 15 29" src="https://cloud.githubusercontent.com/assets/8108361/23191171/86a63d16-f8df-11e6-8d0a-67b3cfd40c3a.png">

**Comment by lakshmantgld** [comment]
Ya got it!! But, why dont we have something like this "asdf by asdf" in one line ? Coz if we have share url, then it all occupies a lot of page.

**Comment by sureshmurali** [comment]
We have lot of space. 
Check this
<img width="347" alt="screen shot 2017-02-22 at 9 32 36" src="https://cloud.githubusercontent.com/assets/8108361/23191602/e6a3738a-f8e1-11e6-9cd0-3fe65d8d5b9a.png">

**Comment by lakshmantgld** [comment]
Share URL Column will be added right?. I thought after adding the Share URL component, it may reduce the space. But from the above pic, it seems ok. Let it be the same

**Comment by sureshmurali** [comment]
I thought separate line will increase readability.

**Comment by sharathvignesh** [comment]
add a "-" before by.
like "Birthday party 
         - by Sharath".

**Comment by sureshmurali** [comment]
Single line
<img width="303" alt="screen shot 2017-02-22 at 11 28 25" src="https://cloud.githubusercontent.com/assets/8108361/23194551/1af392d6-f8f2-11e6-8497-c24852635699.png">

With "-"
<img width="313" alt="screen shot 2017-02-22 at 11 30 29" src="https://cloud.githubusercontent.com/assets/8108361/23194588/5f21621c-f8f2-11e6-9529-86bf3cac97bc.png">

Without "-"
<img width="296" alt="screen shot 2017-02-22 at 11 31 56" src="https://cloud.githubusercontent.com/assets/8108361/23194620/8fe949fa-f8f2-11e6-808b-a6dad87d36a5.png">

Anything is OK for me..

**Comment by lakshmantgld** [comment]
I vote for single line (with font differentiation for name). But it is up to you guys @sharathvignesh @sureshmurali . If you guys think two lines, then I am ok with anything.
