### ISSUE TITLE
Organizer Name and Event name accepts (only) space character as input

### ISSUE THREAD

**Issue by sureshmurali** [Lakshman-LD/LetsMeetUp#116]
Need to write some code to confirm whether user has given a proper organiser name and event name

**Comment by lakshmantgld** [comment]
is it about end space ?

**Comment by sureshmurali** [comment]
I didn't check that..
What i found is it accepts string which has only (one or more) space characters .
Example:
Single space string : " "
Multiple space string : "          "

**Comment by sureshmurali** [comment]
Checked for end space @lakshmantgld .. We also have to eliminate trailing spaces in event name and organizer name.
