### ISSUE TITLE
Iphone SE (smartphone with small display) UI issue

### ISSUE THREAD

**Issue by sureshmurali** [Lakshman-LD/LetsMeetUp#134]
" Free Maybe busy " doesn't align properly with shape symbols

Looks like this: 
Circle   Triangle   Cross
                Free     Maybe     Busy

Our target:
Circle   Triangle   Cross
 Free      Maybe     Busy

Saw this issue in Akira san's iphone SE

**Comment by lakshmantgld** [comment]
But nothing comes in jun-san and ikeda-san iphone right ?
