### ISSUE TITLE
add location details

### ISSUE THREAD

**Issue by sharathvignesh** [Lakshman-LD/LetsMeetUp#34]

**Comment by lakshmantgld** [comment]
Put the google maps link in event page

**Comment by lakshmantgld** [comment]
Added location to eventPage in desktop!! I think slight ah tinkering pannanum. 
Yet to add location in mobile. Have a look at it @sharathvignesh @sureshmurali

**Comment by sureshmurali** [comment]
Added location in both mobile and desktop
