### ISSUE TITLE
Show weather symbol for the dates instead of text

### ISSUE THREAD

**Issue by lakshmantgld** [Lakshman-LD/LetsMeetUp#40]

**Comment by lakshmantgld** [comment]
![screen shot 2016-10-03 at 5 02 20 pm](https://cloud.githubusercontent.com/assets/6481030/19030792/17e9d89c-898b-11e6-95c4-7adda917a565.png)
Here is the type of forecast given by yahoo

**Comment by sureshmurali** [comment]
Check this https://erikflowers.github.io/weather-icons/

**Comment by sureshmurali** [comment]
> 0 wi-tornado
>                 1 wi-strong-wind
>                 2 wi-hurricane
>                 3 wi-thunderstorm
>                 4 wi-thunderstorm
>                 5 wi-snow-wind
>                 6 wi-sleet
>                 7 wi-snow-wind
>                 8 wi-sleet
>                 9 wi-sleet
>                 10 wi-rain-mix
>                 11 wi-showers
>                 12 wi-showers
>                 13 wi-snow
>                 14 wi-snow-wind
>                 15 wi-snow-wind
>                 16 wi-snow
>                 17 wi-snow-wind
>                 18 wi-snow-wind
>                 19 wi-snow-wind
>                 20 wi-snow-wind
>                 21 wi-day-haze
>                 22 wi-smoke
>                 23 wi-strong-wind
>                 24 wi-windy
>                 25 wi-snowflake-cold
>                 26 wi-cloudy
>                 27 wi-night-alt-cloudy
>                 28 wi-day-cloudy
>                 29 wi-night-alt-cloudy
>                 30 wi-day-cloudy
>                 31 wi-night-clear
>                 32 wi-day-sunny
>                 33 wi-stars
>                 34 wi-day-sunny
>                 35 wi-rain-mix
>                 36 wi-hot
>                 37 wi-lightning
>                 38 wi-lightning
>                 39 wi-lightning
>                 40 wi-showers
>                 41 wi-snow
>                 42 wi-rain-mix
>                 43 wi-snow-wind
>                 44 wi-cloud
>                 45 wi-storm-showers
>                 46 wi-rain-mix
>                 47 wi-storm-showers
>                 3200 wi-na
